#!/usr/bin/env node

/**
 * Generate Environment Configuration File
 * 
 * This script reads .env and generates .env-config.js for browser use
 * 
 * Usage: node generate-config.js
 */

const fs = require('fs');
const path = require('path');

const ENV_FILE = '.env';
const CONFIG_FILE = '.env-config.js';

function generateConfig() {
  // Check if .env file exists
  if (!fs.existsSync(ENV_FILE)) {
    console.error(`❌ ${ENV_FILE} not found. Copy from .env.example:`);
    console.error(`   cp .env.example ${ENV_FILE}`);
    console.error(`   Then fill in your actual values.`);
    process.exit(1);
  }

  // Read .env file
  const envContent = fs.readFileSync(ENV_FILE, 'utf-8');
  const envLines = envContent.split('\n');

  const config = {
    DISCORD_CLIENT_ID: null,
    DISCORD_CLIENT_SECRET: null,
    WORKER_URL: null,
    REDIRECT_URI: null,
    GUILD_ID: null,
    REQUIRED_ROLE: null,
    DEPT_ROLES: {},
    ADMINS: {}
  };

  // Parse .env file and build config
  const adminData = {};
  
  for (const line of envLines) {
    const trimmed = line.trim();
    
    // Skip comments and empty lines
    if (!trimmed || trimmed.startsWith('#')) continue;
    
    const [key, value] = trimmed.split('=');
    if (!key || !value) continue;
    
    const k = key.trim();
    const v = value.trim().replace(/^["']|["']$/g, ''); // Remove quotes
    
    if (k === 'DISCORD_CLIENT_ID') config.DISCORD_CLIENT_ID = v;
    else if (k === 'WORKER_URL') config.WORKER_URL = v;
    else if (k === 'REDIRECT_URI') config.REDIRECT_URI = v;
    else if (k === 'GUILD_ID') config.GUILD_ID = v;
    else if (k === 'REQUIRED_ROLE') config.REQUIRED_ROLE = v;
    
    // Parse admin credentials: ADMIN_{DISCORD_ID}_PIN or ADMIN_{DISCORD_ID}_NAME
    if (k.startsWith('ADMIN_') && k.endsWith('_PIN')) {
      const discordId = k.substring(6, k.length - 4);
      if (!adminData[discordId]) adminData[discordId] = {};
      adminData[discordId].pin = v;
    } else if (k.startsWith('ADMIN_') && k.endsWith('_NAME')) {
      const discordId = k.substring(6, k.length - 5);
      if (!adminData[discordId]) adminData[discordId] = {};
      adminData[discordId].name = v;
    }
  }

  // Build ADMINS object
  for (const [id, data] of Object.entries(adminData)) {
    config.ADMINS[id] = {
      pin: data.pin || '',
      name: data.name || 'Administrator'
    };
  }

  // Generate JavaScript file
  const jsContent = `/**
 * GENERATED CONFIGURATION FILE
 * Generated from .env on ${new Date().toISOString()}
 * 
 * This file is automatically generated by generate-config.js
 * Do NOT edit manually - edit .env instead and regenerate
 * 
 * ⚠️  SECURITY: This file contains sensitive data
 *     - Never commit to version control
 *     - Add to .gitignore (already done)
 *     - Treat as confidential
 */

const ENVIRONMENT_CONFIG = ${JSON.stringify(config, null, 2)};

// Make it available to window.CONFIG
if (typeof window !== 'undefined') {
  Object.assign(window.CONFIG || {}, ENVIRONMENT_CONFIG);
}

// Export for Node.js if needed
if (typeof module !== 'undefined' && module.exports) {
  module.exports = ENVIRONMENT_CONFIG;
}
`;

  // Write .env-config.js
  fs.writeFileSync(CONFIG_FILE, jsContent);
  console.log(`✅ Generated ${CONFIG_FILE}`);
  console.log(`   - Loaded ${Object.keys(config.ADMINS).length} admin users`);
  console.log(`   - Worker URL: ${config.WORKER_URL}`);
  console.log(`   - Guild ID: ${config.GUILD_ID}`);
  
  // Security warning
  console.log('\n⚠️  SECURITY WARNING:');
  console.log(`   - ${CONFIG_FILE} contains sensitive credentials`);
  console.log('   - It is already in .gitignore');
  console.log('   - Never commit this file to version control');
  console.log('   - Keep .env file secure and never share');
}

// Run generator
try {
  generateConfig();
} catch (error) {
  console.error('❌ Error generating config:', error.message);
  process.exit(1);
}
